jest.config.js, jest.setup.js, package.json, pnpm-lock.yaml, src/components/common/Text/Text.tsx, src/pages/_app.tsx, src/pages/index.tsx, tests/index/__snapshots__/index.test.tsx.snap, tests/index/index.test.tsx, tsconfig.json
- jest, react-testing-library 세팅을 했습니다. 
-  테스팅 하실 때 참고가 될 수 있을 것 같아 세팅하면서 만들었던 test 폴더와 파일을 함께 push 합니다. (삭제하셔도 무방합니다. )
- package.json의 test 스크립트에서 `passWithNoTest`는 해당 파일이 없을 때 test를 통과시키는 옵션입니다. 
- `pnpm test` 스크립트를 사용하여 테스팅을 진행할 수 있습니다. 
- 제가 작성한 테스트 내용은 해당 파일에 Home이라는 텍스트가 있는지 검사를 진행하고 성공시 `toMatchSnapshot()` 메소드를 이용하여 스냅샷 파일을 만드는 테스트입니다. 
- 임의로 루트에 tests 폴더를 생성해두었는데 test를 진행할 디렉토리는 논의하에 추후 변경하여도 좋을 것 같습니다.
- jest, react testing library 환경 세팅 시 참고 
[https://velog.io/@leehyunho2001/Next.js-TypeScript-환경에서-Jest와-testing-library-사용하기](https://velog.io/@leehyunho2001/Next.js-TypeScript-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-Jest%EC%99%80-testing-library-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
- 스냅샷 테스팅 관련 내용
[https://www.daleseo.com/jest-snapshot/](https://www.daleseo.com/jest-snapshot/)
=> feat: jest, react-testing-library setting

src/components/common/Header/index.tsx, src/components/common/Layout/Layout.tsx, src/pages/index.tsx
- header 컴포넌트를 구현했습니다. 
- Layout 컴포넌트에 양옆 padding 16px를 설정했습니다.
=> feat: header 컴포넌트 구현

src/components/common/Button/Button.tsx, src/constants/button.ts, src/styles/GlobalStyle/reset.ts, src/styles/Theme/Theme.ts
1. `button` 컴포넌트를 리팩토링 했어요.
2. 변경된 디자인 시스템을 적용했어요.
- `variant` 속성을 통해 디자인 시스템에 있는 버튼을 바로 사용할 수 있어요.
- 다음과 같이 사용 가능해요!
```html
<Button variant="largePrimary">버튼</Button>
<Button variant="largePrimary" disabled>버튼</Button>
<Button variant="largeSecondary"><Icon iconName="rightArrow" width={18} height={14} /></Button>
<Button variant="smallButton" disabled width={3.7} height={3.1}>버튼</Button>
```
> ⚠️ `Icon` 컴포넌트에 `color` 속성이 적용되지 않는 문제가 있어요!
=> refactor: button 컴포넌트 리팩토링

package.json, pnpm-lock.yaml, src/components/common/ConfirmModal/index.tsx, src/components/common/Input/index.tsx, src/components/common/Toast/index.tsx, src/hooks/useToast.tsx, src/pages/login/index.tsx
- toast 컴포넌트를 구현했습니다. 
- 자연스러운 애니메이션을 위해 framer-motion을 사용했습니다. 
```ts
const { openToast } = useToast();
const onClick = async (e: any) => {
e.preventDefault();
await openToast({
type: 'success',
title: '안녕하세요.',
});
};
```
- 위와 같은 방식으로 사용할 수 있습니다. 
- error type 
- success type
=> feat: toast component 구현

src/components/common/UserBubble/index.tsx
=> feat: user answer bubble 컴포넌트 구현

src/components/common/InputBubble/index.tsx
- 질문 작성에 사용되는 input 컴포넌트를 구현했습니다.
=> feat: input bubble 컴포넌트 구현

src/components/common/Icon/icons.ts, src/components/common/Icon/icons/warning.svg, src/components/common/Toast/index.tsx, src/pages/index.tsx
- toast 컴포넌트 디자인을 적용했습니다. 
- success type
- danger type
=> feat: toast design system 적용

src/__tests__/utils/testUtils.tsx, src/apis/index.ts, src/components/common/HomeHeader/index.tsx, src/components/signup/SignUpModal.tsx/index.tsx, src/hooks/form/useCheckLoginForm.ts, src/hooks/form/useCheckSignUpForm.tsx, src/hooks/useShowLoginModal.tsx, src/pages/find/[email]/index.tsx, src/pages/find/index.tsx, src/pages/index.tsx, src/pages/login/index.tsx, src/pages/mypage/index.tsx
- 비밀번호 재설정 로직 구현을 완료했습니다. 
- 모달과 toast message를 이용하여 로그인 및 회원가입시 발생할 수 있는 에러를 처리해습니다. 
- 이미 로그인이 되어있는 경우, 홈화면에서 마이페이지로 진입이 가능하도록 연결해두었습니다.
=> feat: 비밀번호 재설정 api fetching

src/components/common/HomeHeader/index.tsx, src/pages/index.tsx
=> feat: onboarding page 작업 완료

src/components/common/Chip/index.tsx
- chip component를 구현했습니다. 
- default / hightlight 로 Chip type을 나누어 개발했습니다. 
- default type
- highlight type
=> feat: chip component 구현

__mocks__/svg.js, jest.config.js, src/__tests__/components/common/Icon.test.tsx, src/__tests__/utils/renderIcon.tsx, src/components/common/Icon/icons.ts
1. `Icon` 컴포넌트 테스트를 추가했어요.
2. `svg` 관련 문제를 해결했어요.
- 기본적인 `render` 테스트를 추가했어요.
- `onClick` 테스트를 추가했어요.
- 아래의 이슈에 상세하게 내용을 정리했어요.
- https://github.com/effective-tech-interview/effective-tech-interview-client/issues/29
=> test: Icon 컴포넌트 테스트 추가

src/hooks/useAnalytics.ts, src/pages/_app.tsx, src/utils/gtag.ts
- GA와 hotjar에 도메인 등록하고 설정을 추가했습니다. 
- 배포 전에 env 파일에 ga, hotjar 환경변수 추가 부탁드려요 !!
=> feat: analytics tools 추가

src/apis/index.ts, src/components/common/AIBubble/index.tsx, src/constants/queryKeys.ts, src/styles/Theme/Theme.ts
1. `AIBubble`에 변경된 디자인을 적용했어요.
- `Text` -> `Chip`으로 변경했어요.
- AI 답변 `Text` 스타일을 변경 적용했어요.
=> refactor: AIBubble 변경된 디자인 적용

package.json, pnpm-lock.yaml, src/apis/index.ts, src/components/common/Button/BottomFixedButton.tsx, src/components/common/Header/index.tsx, src/components/common/Icon/icons/rightArrow.svg, src/components/common/Icon/index.tsx, src/components/question/GoBackModal.tsx, src/pages/_app.tsx, src/pages/_document.tsx, src/pages/category/[categoryId]/index.tsx
- 카테고리 페이지에 헤더를 적용했습니다. 
- 질문 페이지에서 뒤로 가기 버튼 클릭시 모달이 overlay되도록 변경했습니다. 
- favicon과 og tag를 적용했습니다.
=> feat: 헤더 변경 및 favicon, og tag 적용

src/components/common/Button/BottomFixedButton.tsx, src/components/common/Layout/Layout.tsx, src/pages/index.tsx, src/styles/GlobalStyle/GlobalStyle.tsx, src/styles/Theme/Theme.ts
1. `responsive` 디자인을 적용했어요.
- 미디어쿼리 재사용을 위해 `theme`에 따로 정의했어요.
```javascript
// theme
mediaQuery: {
desktop: `@media (min-width: 767px)`,
},
```
https://user-images.githubusercontent.com/79739512/227145881-47ab9921-eb57-4cf7-b306-6599d16d79d2.mov
=> feat: responsive 디자인 적용

next.config.js, src/components/common/Header/index.tsx, src/hooks/query/usePagesQuery.ts, src/hooks/query/useQuestionAnswerQuery.ts, src/hooks/useModal.tsx, src/hooks/useShowLoginModal.tsx, src/pages/_app.tsx, src/pages/_document.tsx
1. 발생한 `error`들을 해결했어요.
- `critical`한 `build` 이슈들을 해결했어요.
- 변경된 `S3 URL`을 `next.config`에 적용했어요.
- 모달에 `Dimme`에 적용되지 않은 반응형 디자인을 적용했어요.
- `title`, `description` 추가를 통해 `SEO`를 보완했어요.
=> hotfix: Release 1.0.0 deploy error 해결

src/apis/client.ts, src/apis/index.ts
=> fix: production url로 변경

src/components/categoryDetail/CategoryDetailBody.tsx, src/components/common/Layout/Layout.tsx, src/components/common/Modal/index.tsx, src/pages/mypage/index.tsx, src/pages/signup/password/[email]/index.tsx, src/styles/GlobalStyle/GlobalStyle.tsx
1. `QA` 내용 적용
- 카테고리 이미지 로딩 속도 최적화를 위해 `priority` 속성을 추가했어요.
- `safari` 및 `firefox`에서 `font`가 적용되지 않던 문제를 해결했어요.
- 계정 문의 및 약관을 추가했어요.
=> hotfix: QA 내용 적용

src/apis/client.ts, src/components/common/Header/index.tsx, src/hooks/form/useCheckLoginForm.ts, src/hooks/useShowLoginModal.tsx
=> fix: token refetch and redirect to login page

src/components/common/HomeHeader/index.tsx, src/pages/find/index.tsx, src/pages/signup/index.tsx
=> hotfix: design qa 해결

src/components/common/HomeHeader/index.tsx, src/pages/find/index.tsx, src/pages/signup/index.tsx
=> fix: design qa 해결 (#52)

src/pages/_document.tsx, src/pages/find/index.tsx, src/pages/signup/index.tsx
=> hotfix: qa design response

next.config.js, src/pages/index.tsx
=> fix: 온보딩 이미지 url 변경

next.config.js, src/pages/index.tsx
=> fix: 온보딩 이미지 url 변경 (#55)

src/components/common/AIBubble/index.tsx, src/components/common/InputBubble/index.tsx, src/components/common/UserBubble/index.tsx
=> style: input style 변경

src/components/common/Chip/index.tsx, src/components/common/HomeHeader/index.tsx, src/pages/category/[categoryId]/index.tsx, src/pages/index.tsx
- onboarding 페이지 변경사항을 반영했습니다.
=> feat: onboarding page 변경

src/components/common/Layout/Layout.tsx, src/styles/GlobalStyle/GlobalStyle.tsx
=> style: layout 수정 및 scrollbar display none

next.config.js, src/components/common/AIBubble/index.tsx, src/components/common/Chip/index.tsx, src/components/common/HomeHeader/index.tsx, src/components/common/InputBubble/index.tsx, src/components/common/Layout/Layout.tsx, src/components/common/UserBubble/index.tsx, src/pages/category/[categoryId]/index.tsx, src/pages/index.tsx, src/styles/GlobalStyle/GlobalStyle.tsx
=> refactor: input style 변경 및 onboarding page 수정 배포

src/components/common/Checkbox/Checkbox.tsx, src/components/common/Checkbox/index.ts, src/pages/signup/password/[email]/index.tsx
1. `checkbox` 컴포넌트를 구현했어요.
2. 회원가입 페이지에 컴포넌트를 적용했어요.
https://user-images.githubusercontent.com/79739512/229346795-94e97e89-201a-4f07-b59b-a45f38e9f690.mov
=> feat: checkbox 컴포넌트 구현

src/components/common/AIBubble/index.tsx, src/components/common/AIBubbleSkeleton/index.tsx
- ai bubble skeleton component를 구현했습니다. 
- suspense까지 적용해보려고 했는데 전역에 suspense가 걸려있어서 그런지  적용이 잘 안되어 .. 일단 컴포넌트 작업한 것만 pr 올립니다 🥲
- 혹시 animation opacity만 변경하는 것이 아니라 wave animation이 더 적합하다고 생각하시면 편하게 말씀주세요 반영하겠습니다! 
- `isSubmitted` 여부에 따라 아래 사진처럼 타입이 나뉘게 됩니다.
=> feat: ai bubble skeleton component 구현

README.md, next.config.js, src/apis/client.ts, src/apis/index.ts, src/components/common/AIBubble/index.tsx, src/components/common/AIBubbleSkeleton/index.tsx, src/components/common/Checkbox/Checkbox.tsx, src/components/common/Checkbox/index.ts, src/components/common/Chip/index.tsx, src/components/common/HomeHeader/index.tsx, src/components/common/InputBubble/index.tsx, src/components/common/Layout/Layout.tsx, src/components/common/QueryClientProvider/QueryClientProvider.tsx, src/components/common/UserBubble/index.tsx, src/hooks/form/useCheckLoginForm.ts, src/hooks/useShowLoginModal.tsx, src/pages/category/[categoryId]/index.tsx, src/pages/index.tsx, src/pages/signup/password/[email]/index.tsx, src/styles/GlobalStyle/GlobalStyle.tsx
=> feat: 로그인 변경 사항 적용 및 배포
